version: "2.1"
services:
    zookeeper:
        image: wurstmeister/zookeeper:latest
        ports:
        - 2181:2181
    kafka:
        image: wurstmeister/kafka:0.10.2.0
        ports:
            - "9092:9092"
        links:
            - zookeeper
        depends_on:
            - zookeeper
        healthcheck:
            test: echo '' | nc -w 1 "kafka" 9093
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_PORT: 9092
            KAFKA_ADVERTISED_HOST_NAME: "kafka"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL,OUTSIDE:PLAINTEXT"
            KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9093,OUTSIDE://localhost:9092"
            KAFKA_LISTENERS: "PLAINTEXT://:9093,OUTSIDE://:9092"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "input:1:1,output:1:1"
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
        volumes:
            - /tmp/kafka-data/data:/data
            - /tmp/kafka-data/logs:/logs
            - /var/run/docker.sock:/var/run/docker.sock

    # anon-kafka-mirror:
    #     image: quay.io/nodefluent/anon-kafka-mirror:latest
    #     restart: always
    #     links:
    #         - kafka
    #     depends_on:
    #         kafka:
    #             condition: service_healthy
    #     environment:
    #         DEBUG: "*"
    #     command: [
    #         "anon-kafka-mirror",
    #         "--consumer-broker-list=kafka:9093",
    #         "--consumer-topic=input",
    #         "--producer-broker-list=kafka:9093",
    #         "--producer-topic=output",
    #         "--consumer-group=test-group",
    #         "--topic-config-file=/config/input.json"
    #         ]
    #     volumes:
    #         - ./examples:/config

    anon-kafka-mirror-local:
        build:
            context: .
            dockerfile: local.Dockerfile
        restart: always
        links:
            - kafka
        depends_on:
            kafka:
                condition: service_healthy
        environment:
            DEBUG: "*"
        command: [
            "node",
            "/usr/src/app/dist/index.js",
            "--consumer-broker-list=kafka:9093",
            "--consumer-topic=input",
            "--producer-broker-list=kafka:9093",
            "--producer-topic=output",
            "--consumer-group=test-group",
            "--topic-config-file=/usr/src/app/examples/input.json"
            ]
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
