version: "2.1"
services:
    zookeeper:
        image: wurstmeister/zookeeper:latest
        ports:
        - 2181:2181
    kafka:
        image: wurstmeister/kafka:0.10.2.0
        ports:
            - "9092:9092"
        links:
            - zookeeper:zookeeper
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_PORT: 9092
            KAFKA_ADVERTISED_HOST_NAME: "kafka"
            KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
            KAFKA_LISTENERS: "PLAINTEXT://:9092"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "input:1:1,output:1:1"
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
        volumes:
            - /tmp/kafka-data/data:/data
            - /tmp/kafka-data/logs:/logs
            - /var/run/docker.sock:/var/run/docker.sock

    anon-kafka-mirror:
        image: quay.io/nodefluent/anon-kafka-mirror:latest
        restart: always
        links:
            - kafka
        depends_on:
            - kafka
        environment:
            DEBUG: "*"
        command: [
            "anon-kafka-mirror", 
            "--consume-broker-list=kafka:9092",
            "--consume-topic=input", 
            "--produce-broker-list=kafka:9092",
            "--produce-topic=output",
            "--consumer-group=test-group",
            "--topic-config-file=/config/input.json"
            ]
        volumes:
            - ./examples:/config
